// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPYSchvtRyHWKBCXECNlktrFKX31zyH1Q',
    appId: '1:42046608803:web:3e67f6ac8e9e916ac1b616',
    messagingSenderId: '42046608803',
    projectId: 'tokio-teste-7a941',
    authDomain: 'tokio-teste-7a941.firebaseapp.com',
    storageBucket: 'tokio-teste-7a941.firebasestorage.app',
    measurementId: 'G-50G0FGB4Y0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdAls2ktXK2j7MknhlCw5V1Klxy7oShVk',
    appId: '1:42046608803:android:56ede1563d846b21c1b616',
    messagingSenderId: '42046608803',
    projectId: 'tokio-teste-7a941',
    storageBucket: 'tokio-teste-7a941.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNwE_AB2nQSSIHVrt_vANmKlWF0k_T4Vw',
    appId: '1:42046608803:ios:137511965ebf26e1c1b616',
    messagingSenderId: '42046608803',
    projectId: 'tokio-teste-7a941',
    storageBucket: 'tokio-teste-7a941.firebasestorage.app',
    iosBundleId: 'com.pedrofo.tokioteste.tokioTeste',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNwE_AB2nQSSIHVrt_vANmKlWF0k_T4Vw',
    appId: '1:42046608803:ios:137511965ebf26e1c1b616',
    messagingSenderId: '42046608803',
    projectId: 'tokio-teste-7a941',
    storageBucket: 'tokio-teste-7a941.firebasestorage.app',
    iosBundleId: 'com.pedrofo.tokioteste.tokioTeste',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPYSchvtRyHWKBCXECNlktrFKX31zyH1Q',
    appId: '1:42046608803:web:025e58a408120ca7c1b616',
    messagingSenderId: '42046608803',
    projectId: 'tokio-teste-7a941',
    authDomain: 'tokio-teste-7a941.firebaseapp.com',
    storageBucket: 'tokio-teste-7a941.firebasestorage.app',
    measurementId: 'G-BM2VDGNZ73',
  );
}
